### ISSUE TITLE
Download error while using service account type credentials

### ISSUE THREAD

**Issue by slawomir-kluz-openx** [abdolence/sbt-gcs-resolver#2]
I'm using service-account type credentials.json which are available as a disk file. There is also environment variable GOOGLE_APPLICATION_CREDENTIALS set - pointing to this file.

The error I got while resolving dependencies is:

[error]   download error: Caught java.io.IOException: Scopes not configured for service account. Scoped should be specified by calling createScoped or passing scopes to constructor. (Scopes not configured for service account. Scoped should be specified by calling createScoped or passing scopes to constructor.) while downloading artifactregistry://us-central1-maven.pkg.dev/PROJECT/REPO/PATH_TO_ARTIFACT.pom

I'm able to resolve the same dependencies using the same setup using official goggle maven/gradle wagon plugins.

Regular user type GCP credentials works as a charm.

**Comment by slawomir-kluz-openx** [comment]
I have noticed that official gradle/maven plugins sets scope while creating credentials object:
https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/blob/master/artifactregistry-auth-common/src/main/java/com/google/cloud/artifactregistry/auth/DefaultCredentialProvider.java

**Comment by abdolence** [comment]
Interesting, give me some time to investigate. Thanks for the report!

**Comment by abdolence** [comment]
@slawomir-kluz-openx thanks for the link and the report. Fixed this in v1.5.0 and tested with my test rep.  Let me know if you still experience this issue.

**Comment by slawomir-kluz-openx** [comment]
@abdolence thanks for the quick fix, I can confirm that the issue is solved.
