### ISSUE TITLE
Local setup

### ISSUE THREAD

**Issue by jczuchnowski** [abdolence/sbt-gcs-resolver#3]
What is the best way for a local setup?

Let's assume a private project with private dependencies kept in Artifact Registry. Once I add the plugin to the project `sbt` will fail if there is no credentials file available. On the other hand each of the developers has gcloud configured and has personal access to the Artifact Registry. Is there a way to use that?

**Comment by jczuchnowski** [comment]
I got a solution from @abdolence on another communication channel.

Turns out gcloud authentication works out of the box. I just needed to run
```
gcloud auth application-default login
```
in addition to the basic gcloud setup.

**Comment by abdolence** [comment]
Slightly updated readme about application default settings to help others with this.
