### ISSUE TITLE
Update google-auth-library-oauth2-http to allow reading external credentials (workload identity federation)

### ISSUE THREAD

**Issue by vertuli** [abdolence/sbt-gcs-resolver#4]
I ran into this error trying to use this plugin to publish to Google Artifact Registry via a GitHub Actions workflow that is otherwise successfully utilizing Workload Identity Federation to provide [external account](https://google-auth.readthedocs.io/en/master/user-guide.html) type credentials:
```
Unable to find/initialise google credentials: java.io.IOException: Error reading credential file from environment variable GOOGLE_APPLICATION_CREDENTIALS, value '[...]': Error reading credentials from stream, 'type' value 'external_account' not recognized. Expecting 'authorized_user' or 'service_account'.. Publishing/resolving artifacts from GCP is disabled.
```
Adding a dependency override to the latest version of `google-auth-library-oauth2-http` in my project's `plugins.sbt` along with the plugin allows `GoogleCredentials` to properly read the external account:
```scala
dependencyOverrides += "com.google.auth" % "google-auth-library-oauth2-http" % "1.3.0"
```

This dependency is coming in via `"com.google.cloud" % "google-cloud-storage" % "1.113.8"` declared in the plugin's `build.sbt`- it seems to be safe to upgrade this to `"com.google.cloud" % "google-cloud-storage" % "2.3.0"`, which will also update the `google-auth-library-oauth2-http` as above.

**Comment by abdolence** [comment]
Hey, thanks for reporting this. Will do

**Comment by abdolence** [comment]
Fixed with https://github.com/abdolence/sbt-gcs-resolver/releases/tag/v1.6.0
Let me know if this is still an issue for you and thanks for detailed report!

**Comment by vertuli** [comment]
It's working without the override now - thanks a lot for getting to this so quickly!
