### ISSUE TITLE
Logging every download spams the logs

### ISSUE THREAD

**Issue by peterrosell** [abdolence/sbt-gcs-resolver#70]
I noticed that when the plugin downloads an artifact it print a log `Receving an artifact from url: <url>". I think this should not be logged as an info log as the plugin replaces the default `HttpURLConnection`, that doesn't do these logs. Nowadays the sbt logs are not that details.

I would suggest that changing the download and upload log to debug level, if they are still needed for troubleshooting.

**Comment by peterrosell** [comment]
I'm gladly creating a PR for this, but maybe not before the weekend. :)

**Comment by abdolence** [comment]
https://github.com/abdolence/sbt-gcs-resolver/releases/tag/v1.11.0
