### ISSUE TITLE
Head request fetched when connecting

### ISSUE THREAD

**Issue by peterrosell** [abdolence/sbt-gcs-resolver#71]
I'm wondering what the purpose of the HEAD request in the [`connect()`](https://github.com/abdolence/sbt-gcs-resolver/blob/c6b9646a8733be9eba5209bddc0b81ffe469ce4b/sbt-gcs-plugin/src/main/scala/org/latestbit/sbt/gcs/artifactregistry/GcsArtifactRegistryUrlConnection.scala#L40) method. When using a custom remote repository in GAR the HEAD request results in a GET request. So the current solution, version `1.10.0` do two request to the upstream repositories.

I see that it sets the [`responsecode`](https://github.com/abdolence/sbt-gcs-resolver/blob/c6b9646a8733be9eba5209bddc0b81ffe469ce4b/sbt-gcs-plugin/src/main/scala/org/latestbit/sbt/gcs/artifactregistry/GcsArtifactRegistryUrlConnection.scala#L55) and `responseMessage` if the head request fails. For me it seems to be a bit confusing if the code that uses the plugin reads these values in different scenarios.

In the download scenario it should work, even if I think the upstream should be connected when the `connect()` method is called and when the `getInputStream` method is called the `inputStream` from the upstream request should be returned. This might make the `getInputStream` method easier as the caching will be handled by the upstream connection. This will also remove the head request as it's not necessary anymore.

In the upload scenario the head request in the `connect()` is a bit odd as the artifact normally doesn't exist before it's uploaded and will always set the `responseCode`  and `responseMessage`. These values are never changed after the `connect()` methods and might be confusing for the code that use the plugin.

I had a look at Google's maven wagon extension and there is a [`openInternalConnection`](https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/blob/46f1d140a1353e41f8fb1e6ac582c192ab048ea4/artifactregistry-maven-wagon/src/main/java/com/google/cloud/artifactregistry/wagon/ArtifactRegistryWagon.java#L75) method that don't do any connection, only prepare the factory. In the [`getInputStream`](https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/blob/46f1d140a1353e41f8fb1e6ac582c192ab048ea4/artifactregistry-maven-wagon/src/main/java/com/google/cloud/artifactregistry/wagon/ArtifactRegistryWagon.java#L58) method the request is created and its inputStream is returned. 

Based on this I think the HEAD request can be removed in the connect method.

And once again thanks for building this plugin. :heart:

**Comment by abdolence** [comment]
Thanks for the feedback, help with this and kind words!

**Comment by peterrosell** [comment]
I will have a look next week. If you look at the [connect() code](https://github.com/abdolence/sbt-gcs-resolver/pull/68/files#diff-a06acb58f55314fcef9b3d70ac17a16a5c13098eb2565fdcd191e2ae62713d8aR44-R50) in my old PR you see that I did that change and it worked good.

**Comment by peterrosell** [comment]
Are you planing to make a new release soon? I would like to reduce our load on GAR. :)

**Comment by abdolence** [comment]
>  Are you planing to make a new release soon? I would like to reduce our load on GAR. :)

Haha, I don't think if Google even notices this ever, but here you go:
https://github.com/abdolence/sbt-gcs-resolver/releases/tag/v1.11.0

It is usually requires some time until maven repo caches contain the new ver, but I did my part :)

**Comment by peterrosell** [comment]
Thanks a lot!  
We have had some problems that might been related to hitting the quota. Maybe on upstream remote repos, but it has been hard to pinpoint. It has got better with the new version and now I also added caching of the fetched artifacts so the problem has reduced, but I like to optimize. :joy:
