### ISSUE TITLE
SBT plugin from GAR

### ISSUE THREAD

**Issue by acheek24** [abdolence/sbt-gcs-resolver#88]
I've got things working for code dependencies that we have living in GAR. We also have a plugin that lives there too so I was wondering if you had any ideas on if it's possible to use the resolver plugin to pull that down.  

IE
```
addSbtPlugin("org.latestbit" % "sbt-gcs-plugin" % "1.12.0")
addSbtPlugin("com.ourorg"  % "our-plugin"         % "1.0.0")
```

Right now, probably as expected, it won't try to resolve our plugin via GAR despite various attempts at setting the resolver. Thanks for any tips!

**Comment by abdolence** [comment]
Hey, it is usually done using multiple levels of directories for sbt.
So, it is about the support from sbt itself.

You should create another directory in project, so it would be one more file at:
`project/project/plugins.sbt` which should contain 
`addSbtPlugin("org.latestbit" % "sbt-gcs-plugin" % "1.12.0")`
then it can be used to fetch plugins themselves.

**Comment by acheek24** [comment]
🎉 That worked. Thanks!
